---
- name: install nginx
  hosts: web
  become: yes

  tasks:
  - name: Ensure nginx package is present
    apt:
     name: nginx
     state: present

  - name: Ensure index.html is present
    copy:
     src: index.html
     dest: /var/www/html

  - name: Ensure nginx started
    service:
     name: nginx
     state: started

- name: install db
  hosts: db
  become: yes

  tasks:
  - name: Ensure postgres is present
    apt:
     name: postgresql
     state: present

  - name: Ensure postgres is started
    service:
     name: postgresql
     state: started
