---
# tasks file for deploy
- name: Ensure tomcat9 is present on deploy node
  apt:
    name: tomcat9
    state: present
#- name: Transfer artifact to deploy nodes
#  synchronize:
#    src: "{{ loc_path }}/boxfuse-sample-java-war-hello/target/hello-1.0.war"
#    dest: /var/lib/tomcat9/webapps/hello-1.0.war
#    mode: pull

