version: '2'
services:
  builder:
    build:
      context: builder/
      args:
        - BUILD_PATH
        - BUILD_OUT
        - DEST_PATH
    volumes:
      - ./artifacts:${DEST_PATH}/${BUILD_OUT}
#    networks:
#      - task7

  deployer:
    build:
      context: deployer/
      args:
        - DEST_PATH
    ports:
      - "8080:8080"
    volumes:
      - ./artifacts:${DEST_PATH}/tomcat/webapps/
#    networks:
#      - task7
    depends_on:
      - builder

#networks:
#  task7:
#    driver: bridge
