---
- name: manage hosts
  hosts: localhost
  connection: local
  vars:
    cloud_machine_ip: "{{ lookup('file', 'cloud_machine_ip.info') }}"
  tasks:

  - name: Add host to group 'build'
    add_host:
      name: "{{ cloud_machine_ip }}"
      groups: build
      ansible_ssh_private_key_file: ~/.ssh/aws3.pem

- name: build
  hosts: build
  remote_user: ubuntu
  become: true
  gather_facts: False
  tasks:

  - name: Wait for system to become reachable
    wait_for_connection:
     delay: 30
     timeout: 30
  - name: Ensure needed packages is presented on build node
    apt:
     name: "{{ item }}"
     state: present
     update_cache: yes
    with_items:
     - maven
     - git
     - default-jdk
     - mc
     - docker.io

  - name: Cloning sources to build node over https
    git:
     repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
     dest: "tmp/boxfuse-sample-java-war-hello"
     clone: yes
     update: no

  - name: Building war file
    shell: cd "tmp/boxfuse-sample-java-war-hello" && mvn package

  - name: Copy artifact
    copy:
     src: "tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war"
     dest: /tmp

  - name: Copy Dockerfile
    copy:
     src: "/home/final_task/Dockerfile"
     dest: /tmp

  - name: Build container image
    docker_image:
      name: boxfuse:v1.0
      build:
        path: /tmp
        source: build
      state: present
