---
- name: manage hosts
  hosts: localhost
  connection: local
  vars:
    cloud_machine_ip: "{{ lookup('file', 'cloud_machine_ip.info') }}"
  tasks:

  - name: Add host to group 'build'
    add_host:
      name: "{{ cloud_machine_ip }}"
      groups: build
      ansible_ssh_private_key_file: ~/.ssh/aws3.pem

- name: build
  hosts: build
  remote_user: ubuntu
  become: true
  gather_facts: False
  tasks:

  - name: Wait for node to become reachable
    wait_for_connection:
     delay: 30
     timeout: 30

  - name: Install needed packages
    apt:
     name: ['maven', 'git', 'default-jdk', 'mc', 'docker.io', 'python3-docker', 'python3', 'python3-pip']
     state: present
     update_cache: yes

  - name: Cloning sources
    git:
     repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
     dest: "tmp/boxfuse-sample-java-war-hello"
     clone: yes
     update: no

  - name: Building war file
    shell: cd "tmp/boxfuse-sample-java-war-hello" && mvn package

  - name: Copy artifact on remote
    copy:
     remote_src: yes
     src: "tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war"
     dest: tmp

  - name: Copy Dockerfile to remote
    copy:
     src: "/home/final_task/Dockerfile"
     dest: tmp

  - name: Build container image
    docker_image:
      name: boxfuse:v1.0
      build:
        path: tmp
      source: build
      state: present
