---
- name: install build environment
  hosts: local

  tasks:
  - name: Ensure git is present
    apt:
     name: git
     state: present
  - name: Ensure default-jdk is present
    apt:
     name: default-jdk
     state: present
  - name: Ensure maven is present
    apt:
     name: maven
     state: present

  - name: Cloning sources to master node
    git:
     repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
     dest: /usr/local
     clone: yes
     update: yes