FROM alpine:3.7
RUN apk add git openjdk8 maven docker bash
#RUN mkdir -p /usr/local/build \
# && cd /usr/local/build \
# && git clone https://github.com/indbs/boxfuse_cloned.git \
# && cd /usr/local/build/boxfuse_cloned \
# && mvn package
CMD /bin/bash
